### ISSUE TITLE
Please import the branch from tfoote/orbbec_ros

### ISSUE THREAD

**Issue by tfoote** [orbbec/OpenNI2#1]
This is the branch used for the ROS packages. It's currently resides on my fork: https://github.com/tfoote/OpenNI2/tree/orbbec_ros

Since this is a slightly diverged branch I cannot submit it as a PR it needs to be pushed as a new branch by someone with push access. 

Or if someone could create a branch with an appropriate name I'd be happy to submit it as a pull request against that branch.

**Comment by BrannonKing** [comment]
I see your changes in the ros branch history. Is this done?

**Comment by tfoote** [comment]
Yeah, it looks like they are there. Closing.
